.github/workflows/release.yml

put release yml back

---

pom.xml

update core cc and farao dependencies

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
pom.xml

prepare release

---

.github/workflows/ci-commit.yml
.github/workflows/ci-master.yml
.github/workflows/release.yml
Dockerfile
pom.xml

Update java 17

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGenerator.java

improve the use of minio starter

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/F305XmlGenerator.java

No
Bug fix
Intervals in the F305 are going from x:30 to y:30 instead of x:00 to y:00
Fixed (and also renamed class so it's more obvious what it's generating)
No
**Other …

fix intervals in F305 to start at x:00 and finish at y:00

---

.github/workflows/ci-master.yml

remove broadcast event from ci master

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGenerator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/ZipUtil.java
gridcapa-core-cc-post-processing-app/src/main/resources/logback.xml

Improve exceptions handling and logs

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/CoreCCPostProcessingHandler.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/F305XmlGenerator.java

Avoid zombie state after exception and improve export robustness

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java

Avoid exporting 303 file if in error, just skip

---

pom.xml

upgrade farao dependencies from 1.21.1 to 1.22.0

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Clusterizer.java
pom.xml

upgrade farao parent, core cc and task manager versions

---

pom.xml

upgrade core cc version

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/F305XmlGenerator.java

fix failing F305 if TS is in error (no outputs)

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/CoreCCMetadataGenerator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/RaoMetadata.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/ZipUtil.java

fix failing post processor in case of missing metadata

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java

fix outputs filename

---

gridcapa-core-cc-post-processing-app/pom.xml
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Clusterizer.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303Info.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGenerator.java
gridcapa-core-cc-post-processing-app/src/main/resources/logback.xml
pom.xml

upgrade farao dependencies and farao parent

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRulesTest.java

fix version

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRulesTest.java

Zip and output Rao Results

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGenerator.java
gridcapa-core-cc-post-processing-app/src/main/resources/crac/cracCreationParameters.json
pom.xml

Upgrade to farao dependencies 1.26.0 and apply changes required from the following PR : https://github.com/powsybl/powsybl-open-rao/pull/886
(if any of …

Upgrade to farao-dependencies 1.26.0

---

pom.xml

Upgrade farao dependencies version

---

pom.xml

Upgrade core cc runner release version

---

gridcapa-core-cc-post-processing-app/pom.xml
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/configuration/CoreCCPostProcessingConfiguration.java
pom.xml

Upgrade Spring Boot 3.2 and Spring Cloud 2023

---

pom.xml

Upgrade olf 1.8.2 to master

---

pom.xml

Upgrade farao dependencies 1.29.0

---

gridcapa-core-cc-post-processing-app/src/main/resources/application.yml

set default group param correctly in spring cloud

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/CoreCCPostProcessingHandler.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/CoreCCPostProcessingHandlerTest.java

Fix date used to check whether all tasks of the day are finished

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/Utils.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator1Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator2Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRulesTest.java
pom.xml

Use max TS run count as BD outputs revision number

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/Utils.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator1Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator2Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRulesTest.java
pom.xml

revert last commit

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadService.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRules.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/CoreCCPostProcessingHandlerTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/PostProcessingServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/Utils.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator1Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator2Test.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/ZipAndUploadServiceTest.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/util/NamingRulesTest.java
pom.xml

Handle run version for output files versioning rebased

---

gridcapa-core-cc-post-processing-app/src/main/resources/application.yml
gridcapa-core-cc-post-processing-app/src/test/resources/application.yml

Harmonize application.yml

---

pom.xml

Upgrade core cc post processing to olf 1.11.1

---

gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Clusterizer.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/DailyF303Generator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGenerator.java
gridcapa-core-cc-post-processing-app/src/main/java/com/farao_community/farao/core_cc_post_processing/app/util/CracUtil.java
gridcapa-core-cc-post-processing-app/src/test/java/com/farao_community/farao/core_cc_post_processing/app/services/HourlyF303InfoGeneratorTest.java
pom.xml

Upgrade farao-dependencies to v1.33.0

---

pom.xml

Back to olf 1.12.2

---

pom.xml

upgrade core cc runner version and farao dependencies version

---

pom.xml

Upgrade farao-dependencies to 1.38.2
